"""empty message

Revision ID: 1ab978c955d1
Revises: 
Create Date: 2024-05-04 00:50:51.860967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab978c955d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_code',
    sa.Column('code', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('weather_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('wind_speed', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('surface_pressure', sa.Integer(), nullable=True),
    sa.Column('type_weather', sa.Integer(), nullable=True),
    sa.Column('rain_size_precipitation', sa.Integer(), nullable=True),
    sa.Column('snow_size_precipitation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_weather'], ['weather_code.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_history')
    op.drop_table('weather_code')
    # ### end Alembic commands ###
