"""empty message

Revision ID: 97af68a5b4b2
Revises: 1ab978c955d1
Create Date: 2024-05-04 00:59:03.262283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97af68a5b4b2'
down_revision: Union[str, None] = '1ab978c955d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_history', sa.Column('weather_code', sa.Integer(), nullable=True))
    op.drop_constraint('weather_history_type_weather_fkey', 'weather_history', type_='foreignkey')
    op.create_foreign_key(None, 'weather_history', 'weather_code', ['weather_code'], ['code'])
    op.drop_column('weather_history', 'type_weather')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_history', sa.Column('type_weather', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weather_history', type_='foreignkey')
    op.create_foreign_key('weather_history_type_weather_fkey', 'weather_history', 'weather_code', ['type_weather'], ['code'])
    op.drop_column('weather_history', 'weather_code')
    # ### end Alembic commands ###
